DROP TABLE IF EXISTS ACCOUNTS;
DROP TABLE IF EXISTS STATEMENTS;

CREATE TABLE ACCOUNTS (
  id VARCHAR(250)   PRIMARY KEY,
  account_type VARCHAR(250) NOT NULL,
  account_number  VARCHAR(250) NOT NULL,
  USER_ID VARCHAR(250) NOT NULL,
  iban VARCHAR(250) NOT NULL,
  balance VARCHAR(250) NOT NULL,
  currency VARCHAR(250) NOT NULL
);


CREATE TABLE STATEMENTS(
  id VARCHAR(250)  PRIMARY KEY,
  account_id VARCHAR(250) NOT NULL,
  account_number  VARCHAR(250) NOT NULL,
  description VARCHAR(250) NOT NULL,
  amount VARCHAR(250) NOT NULL,
  date_of_trs VARCHAR(250) NOT NULL,
  currency VARCHAR(250) NOT NULL
);

ALTER TABLE ACCOUNTS
    ADD FOREIGN KEY (USER_ID) 
    REFERENCES USERS(id);

ALTER TABLE STATEMENTS
    ADD FOREIGN KEY (account_id) 
    REFERENCES ACCOUNTS(id);


 
